const langs_const = {
    'en': {
        lang: 'en',
        general: {
            searchBar: 'Search by NIF',
            main_header: 'Upload xlsx file to search a list of NIFs',
            results_header: 'Wait until your information is being processed',
            search_header: 'Search results',
            recent_header: 'Recent queries',
            click_upload: 'Click here to upload file',
            none_file: 'No file selected yet',
            submit: 'Submit',
            file_submitted: 'File submitted: ',
            file_selected: 'Click submit button to send. File selected: ',
            wait_until_complete: 'Wait until everything is proccessing. This can take a while.',
            position_queue: 'Queue position: ',
            status: 'Status: ',
            total_search: 'NIFs quantity: ',
            progress: 'Progress: ',
            waiting_queue: 'Waiting for the queue',
            started: 'Started',
            finished: 'Finished',
            download_ready: 'Data has been generated. Your file will be downloaded in a few. If nothing happens click here.',
            click_download: 'Data is already generated. Click here to download the results.',
            razon_social: 'Company Name',
            domicilio: 'Address',
            calle: 'Street',
            codigo_postal: 'ZIP Code',
            ciudade: 'City',
            provincia: 'Province',
            telefono: 'Telephone Number',
            registro: 'Register',
            website: 'Website',
        },
        errors: {
            multipleFiles: 'You can not choose more than one file.',
            file_large: 'File is too large (MAX: 2MB). Click here to try again.',
            invalid_template: 'Invalid Excel template. Click here to try again.',
            no_files: 'You need to send at least one file. Click here to try again.',
            unexpected: 'Unexpected error. Click here to try again.',
            not_found_hash: 'Hash has not been found. Please, try again.',
            invalid_hash: 'Invalid hash. Please, try again.',
            file_not_found: 'File not found. Please, try again.',
            nif_not_found: 'NIF has not been found at infocif.es.',
        },
        success: {
            uploaded_click_here: 'Your NIFs list is being processing now. You will be redirected. If nothing happens, click here.',
            found_hash: 'Hash has been found',
        }
    },
    'es': {
        lang: 'es',
        general: {
            searchBar: 'Búsqueda por NIF',
            main_header: 'Cargue el archivo de Excel para buscar una lista de NIFs',
            results_header: 'Espere hasta que se procese su información',
            search_header: 'Resultados de la búsqueda',
            recent_header: 'Búsqueda recentes',
            click_upload: 'Clic aquí para cargar el archivo',
            none_file: 'Ningún archivo seleccionado',
            submit: 'Enviar',
            file_submitted: 'Archivo seleccionado: ',
            file_selected: 'Clic en enviar para continuar. Archivo seleccionado: ',
            wait_until_complete: 'Espere mientras se procesa todo. Esto puede tardar un rato. Esto puede tomar un tiempo.',
            position_queue: 'Posición en la cola: ',
            status: 'Status: ',
            total_search: 'Cantidad de NIFs: ',
            progress: 'Progreso: ',
            waiting_queue: 'Esperando en la fila',
            started: 'Empezado',
            finished: 'Completo',
            download_ready: 'La información fue generada. Tu archivo se descargará pronto. Si no pasa nada, haga clic aquí.',
            click_download: 'La información fue generada. Clic aquí para descargar los resultados.',
            razon_social: 'Razón Social',
            domicilio: 'Domicilio',
            calle: 'Calle',
            codigo_postal: 'Código Postal',
            ciudade: 'Ciudade',
            provincia: 'Provincia',
            telefono: 'Teléfono',
            registro: 'Registro',
            website: 'Website',
        },
        errors: {
            multipleFiles: 'No puede seleccionar más de un archivo.',
            file_large: 'El archivo es demasiado grande (MAX: 2MB). Clic aquí para volver a intentarlo.',
            invalid_template: 'Template inválido. Clic aquí para volver a intentarlo.',
            no_files: 'Necesitas seleccionar al menos un archivo. Clic aquí para volver a intentarlo.',
            unexpected: 'Error inesperado. Clic aquí para volver a intentarlo.',
            not_found_hash: 'No se encontró el hash. Por favor, inténtalo de nuevo.',
            invalid_hash: 'Hash inválido. Por favor, inténtalo de nuevo.',
            file_not_found: 'Archivo no encontrado. Por favor, inténtalo de nuevo.',
            nif_not_found: 'No se encontró el NIF en infocif.es.',
        },
        success: {
            uploaded_click_here: 'Su lista de NIFs se está procesando ahora. Serás redirigido automáticamente. Si no pasa nada, haga clic aquí.',
            found_hash: 'Se ha encontrado hash',
        }
    },
    'pt': {
        lang: 'pt',
        general: {
            searchBar: 'Pesquisar por NIF',
            main_header: 'Faça o upload do arquivo Excel para pesquisar uma lista de NIFs',
            results_header: 'Aguarde até que a informação seja processada',
            search_header: 'Resultados da pesquisa',
            recent_header: 'Pesquisas recentes',
            click_upload: 'Clique aqui para fazer o upload',
            none_file: 'Nenhum arquivo selecionado',
            submit: 'Enviar',
            file_submitted: 'Arquivo anexado: ',
            file_selected: 'Clique em enviar para prosseguir. Arquivo selecionado: ',
            wait_until_complete: 'Aguarde enquanto tudo está sendo processado. Isso pode levar um tempo.',
            position_queue: 'Posição na fila: ',
            status: 'Estado: ',
            total_search: 'Quantidade de NIFs: ',
            progress: 'Progresso: ',
            waiting_queue: 'Aguardando pela fila',
            started: 'Iniciado',
            finished: 'FInalizado',
            download_ready: 'Os dados foram gerados. Seu arquivo será baixado em breve. Se nada acontecer, clique aqui.',
            click_download: 'Os dados já foram gerados. Clique aqui para baixar os resultados.',
            razon_social: 'Razão Social',
            domicilio: 'Endereço',
            calle: 'Rua',
            codigo_postal: 'CEP',
            ciudade: 'Cidade',
            provincia: 'Província',
            telefono: 'Telefone',
            registro: 'Registro',
            website: 'Website',
        },
        errors: {
            multipleFiles: 'Você não pode selecionar mais de um arquivo',
            file_large: 'O arquivo é muito grande (MAX: 2MB). Clique aqui para tentar novamente.',
            invalid_template: 'Template inválido. Clique aqui para tentar novamente.',
            no_files: 'Você precisa anexar pelo menos um arquivo. Clique aqui para tentar novamente.',
            unexpected: 'Erro inesperado. Clique aqui para tentar novamente.',
            not_found_hash: 'O hash não foi encontrado. Por favor, tente novamente.',
            invalid_hash: 'Hash inválido. Por favor, tente novamente.',
            file_not_found: 'Arquivo não encontrado. Por favor, tente novamente.',
            nif_not_found: 'O NIF não foi encontrado em infocif.es.',
        },
        success: {
            uploaded_click_here: 'Sua lista de NIF está sendo processada agora. Você será redirecionado automaticamente. Se nada acontecer, clique aqui.',
            found_hash: 'Hash encontrado',
        }
    },
}

module.exports = langs_const;